# Generated by Django 5.2 on 2026-04-29 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Student",
            new_name="product",
        ),
    ]
